name: Fullstack ChatApp CI/CD to ECR

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set build number (short SHA)
        run: echo "BUILD_NUM=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build, tag, and push frontend image
        run: |
          IMAGE_URI=223319878711.dkr.ecr.ap-south-1.amazonaws.com/rahulrepo/frontend
          docker build -t $IMAGE_URI:$BUILD_NUM ./frontend
          docker tag $IMAGE_URI:$BUILD_NUM $IMAGE_URI:latest
          docker push $IMAGE_URI:$BUILD_NUM
          docker push $IMAGE_URI:latest

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set build number (short SHA)
        run: echo "BUILD_NUM=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build, tag, and push backend image
        run: |
          IMAGE_URI=223319878711.dkr.ecr.ap-south-1.amazonaws.com/rahulrepo/backend
          docker build -t $IMAGE_URI:$BUILD_NUM ./backend
          docker tag $IMAGE_URI:$BUILD_NUM $IMAGE_URI:latest
          docker push $IMAGE_URI:$BUILD_NUM
          docker push $IMAGE_URI:latest
