name: Fullstack ChatApp CI/CD to ECR (Latest + Version Tag)

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version (e.g. v1.0.0)'
        required: true

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push frontend (latest + version)
        run: |
          IMAGE_URI=223319878711.dkr.ecr.ap-south-1.amazonaws.com/rahulrepo/frontend
          VERSION=${{ github.event.inputs.version }}
          docker build -t $IMAGE_URI:latest -t $IMAGE_URI:$VERSION ./frontend
          docker push $IMAGE_URI:latest
          docker push $IMAGE_URI:$VERSION

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend (latest + version)
        run: |
          IMAGE_URI=223319878711.dkr.ecr.ap-south-1.amazonaws.com/rahulrepo/backend
          VERSION=${{ github.event.inputs.version }}
          docker build -t $IMAGE_URI:latest -t $IMAGE_URI:$VERSION ./backend
          docker push $IMAGE_URI:latest
          docker push $IMAGE_URI:$VERSION
